In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
train_data=pd.read_csv("/content/drive/MyDrive/ML_Assignment2/netflix/TrainingRatings.txt", names=["MovieID", "UserID", "Rating"])
train_data.head()

MovieID   UserID  Rating
0        8  1744889     1.0
1        8  1395430     2.0
2        8  1205593     4.0
3        8  1488844     4.0
4        8  1447354     1.0

In [12]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3255352 entries, 0 to 3255351
Data columns (total 3 columns):
 #   Column   Dtype  
---  ------   -----  
 0   MovieID  int64  
 1   UserID   int64  
 2   Rating   float64
dtypes: float64(1), int64(2)
memory usage: 74.5 MB


In [6]:
user_item_df=pd.pivot_table(train_data, values="Rating", index="UserID", columns="MovieID").fillna(0)
user_item_df.head()

MovieID  8      28     43     48     61     ...  17725  17728  17734  17741  17742
UserID                                      ...                                   
7          5.0    4.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
79         0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
199        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
481        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
769        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 1821 columns]

In [14]:
test_data=pd.read_csv("/content/drive/MyDrive/ML_Assignment2/netflix/TestingRatings.txt", names=["MovieID", "UserID", "Rating"])
test_data.head()

MovieID   UserID  Rating
0        8   573364     1.0
1        8  2149668     3.0
2        8  1089184     3.0
3        8  2465894     3.0
4        8   534508     1.0

In [15]:
# make a copy of train and test datasets
dummy_train = train_data.copy()
dummy_test = test_data.copy()

dummy_train['Rating'] = dummy_train['Rating'].apply(lambda x: 0 if x > 0 else 1)
dummy_test['Rating'] = dummy_test['Rating'].apply(lambda x: 1 if x > 0 else 0)

In [16]:
# The movies not rated by user is marked as 1 for prediction 
dummy_train = dummy_train.pivot(index = 'UserID', columns = 'MovieID', values = 'Rating').fillna(1)

# The movies not rated by user is marked as 0 for evaluation 
dummy_test = dummy_test.pivot(index ='UserID', columns = 'MovieID', values = 'Rating').fillna(0)

In [8]:
dummy_train.head()

MovieID  8      28     43     48     61     ...  17725  17728  17734  17741  17742
UserID                                      ...                                   
7          0.0    0.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0    1.0
79         1.0    1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0    1.0
199        1.0    1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0    1.0
481        1.0    1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0    1.0
769        1.0    1.0    1.0    1.0    1.0  ...    1.0    1.0    1.0    1.0    1.0

[5 rows x 1821 columns]

In [9]:
dummy_test.head()

MovieID  8      28     43     48     61     ...  17725  17728  17734  17741  17742
UserID                                      ...                                   
7          0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
79         0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
199        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
481        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
769        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 1701 columns]

In [7]:

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_item_df)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)
print(user_similarity.shape)

[[1.         0.41957691 0.39019949 ... 0.37195276 0.37758772 0.46980239]
 [0.41957691 1.         0.36185935 ... 0.22611836 0.35119518 0.41948276]
 [0.39019949 0.36185935 1.         ... 0.39178429 0.30393094 0.29161915]
 ...
 [0.37195276 0.22611836 0.39178429 ... 1.         0.22180705 0.23167963]
 [0.37758772 0.35119518 0.30393094 ... 0.22180705 1.         0.41185017]
 [0.46980239 0.41948276 0.29161915 ... 0.23167963 0.41185017 1.        ]]
(28978, 28978)


## **Predicting user rating on movies**

In [11]:
user_predicted_ratings = np.dot(user_similarity, user_item_df)
user_predicted_ratings

array([[ 3341.43763035, 18591.47966584,    42.17591148, ...,
           38.30482378,  1136.24922938,   249.85555121],
       [ 2773.97934545, 17298.28155045,    36.69013861, ...,
           29.87368244,   986.38070373,   226.81959826],
       [ 3066.32042888, 16093.84008091,    38.57984824, ...,
           31.67996951,  1123.00524534,   199.024523  ],
       ...,
       [ 2955.71888145, 13777.28181744,    35.56452708, ...,
           35.71970978,  1025.045092  ,   188.76975814],
       [ 2581.52945855, 15348.31543553,    31.50126594, ...,
           27.89067041,   915.89882898,   201.05502611],
       [ 2964.29837175, 18709.48699359,    40.29063791, ...,
           30.75150511,  1107.17348327,   240.07688208]])

In [12]:
# np.multiply for cell-by-cell multiplication 

user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)
user_final_ratings.head()

MovieID        8             28     ...        17741       17742
UserID                              ...                         
7           0.000000      0.000000  ...  1136.249229  249.855551
79       2773.979345  17298.281550  ...   986.380704  226.819598
199      3066.320429  16093.840081  ...  1123.005245  199.024523
481      2592.534547  16111.845425  ...  1043.299604  195.223276
769      3076.977406  14646.360233  ...  1053.086065  198.542688

[5 rows x 1821 columns]

In [8]:
user_item_test_df=pd.pivot_table(test_data, values="Rating", index="UserID", columns="MovieID").fillna(0)
test_user_similarity = cosine_similarity(user_item_test_df)
test_user_similarity[np.isnan(test_user_similarity)] = 0

print(test_user_similarity)

print(test_user_similarity.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(27555, 27555)


In [9]:
user_predicted_ratings_test = np.dot(test_user_similarity, user_item_test_df)
user_predicted_ratings_test

array([[ 3.84682955,  5.88114317,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 5.2824231 , 13.63369665,  0.        , ...,  0.        ,
         0.73284578,  0.        ],
       [ 1.56549132, 13.61924128,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 2.05468302, 13.5284027 ,  0.        , ...,  0.        ,
         2.36623487,  0.        ],
       [ 5.43083768, 21.83047084,  0.        , ...,  0.        ,
         1.4720338 ,  0.91652764],
       [ 1.34588189,  8.69301276,  0.        , ...,  0.        ,
         0.76167761,  1.02597835]])

In [17]:
test_user_final_rating = np.multiply(user_predicted_ratings_test, dummy_test)
test_user_final_rating.head()

MovieID  8      28     43     48     61     ...  17725  17728  17734  17741  17742
UserID                                      ...                                   
7          0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
79         0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
199        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
481        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
769        0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 1701 columns]

In [19]:
X = test_user_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [20]:
# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

100478

In [21]:
test=pd.pivot_table(test_data, values="Rating", index="UserID", columns="MovieID")
test.head()

MovieID  8      28     43     48     61     ...  17725  17728  17734  17741  17742
UserID                                      ...                                   
7          NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
79         NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
199        NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
481        NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
769        NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN

[5 rows x 1701 columns]

In [22]:
# RMSE Score

diff_sqr_matrix = (test - pred)**2
sum_of_squares_err = diff_sqr_matrix.sum().sum() # df.sum().sum() by default ignores null values

rmse = np.sqrt(sum_of_squares_err/total_non_nan)
print(rmse)

1.3975080554168327


In [23]:
# Mean abslute error

mae = np.abs(pred - test).sum().sum()/total_non_nan
print(mae)

1.176214030356687
